/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://4swn2sx4znarpjr56xia3nlqba.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qeswxhbdxvdhnn2xdupi7aduuy",
    "aws_cognito_identity_pool_id": "us-east-1:5d2ebac6-623d-4798-b12d-d038471a31de",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_D6OHELDul",
    "aws_user_pools_web_client_id": "2jbarl24ld324c0vmv6u4eqvnm",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "Auth": {
        "Cognito": {
            "region": "us-east-1",
            "userPoolId": "us-east-1_4PIyHXV77",
            "userPoolClientId": "3uh0uogbiksicgn7pknj1tk8g6"
        },
        "userPoolWebClientId": "3uh0uogbiksicgn7pknj1tk8g6",
        "mandatorySignIn": true
    }
};


export default awsmobile;
