/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://4swn2sx4znarpjr56xia3nlqba.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qeswxhbdxvdhnn2xdupi7aduuy",
    "Auth": {
        "Cognito": {
            "region": "us-east-1",
            "userPoolId": "us-east-1_4PIyHXV77",
            "userPoolClientId": "3uh0uogbiksicgn7pknj1tk8g6"
        },
        "userPoolWebClientId": "3uh0uogbiksicgn7pknj1tk8g6",
        "mandatorySignIn": true
    }
};


export default awsmobile;
